version: 2

updates:
  - package-ecosystem: pip
    directory: "/requirements"
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "sphinx"
      - dependency-name: "sphinx_rtd_theme"
      - dependency-name: "readthedocs-sphinx-search"
